#!/bin/python3

from hashlib import md5
from sys import argv

flag_hashes = [
    'a414bccc40a40462a42a97187561d9b2',
    '3ccba02404bbdc4c4386f55d8c072a0c',
    '368c0ecbd9328719af12b8cd6d810142',
    'fdc445bfded41f427ec06c9d9135be80'
]

def usage():
    print("""Description:
    This program will verify if the flag you found is the correct one
    Don't forget the single quotes around the flag ( ' ) otherwise characters
    like ( ! ) or ( $ ) might change your argument in bash
Usage:
    ./verify 'passwd{??????????????}'

if you want tips, try running the program with -tip
""")

def tip():
    print("get good lol")

if len(argv) != 2 or "-h" in argv:
    usage()
    exit(0)

if "-tip" in argv:
    tip()
    exit(0)

h = md5(argv[1].encode('utf-8')).hexdigest()

if h in flag_hashes:
    print("Success! You validated flag nb %d" % (flag_hashes.index(h) + 1))
else:
    print("Failed! try again")
