#!/bin/python3

from hashlib import md5
from sys import argv

flag_hashes = [
    '5ff4c454d986686237409079e4566d3d',
    '376340e2bc11c02193b77da545a58d1f',
    'de290e34c6e0c5e09e4349ee2e6ef50e',
    '3ebcefe29b1011ff3923e7149f7a4e46'
]

def usage():
    print("""Description:
    This program will verify if the flag you found is the correct one
    Don't forget the single quotes around the flag ( ' ) otherwise characters
    like ( ! ) or ( $ ) might change your argument in bash
Usage:
    ./verify 'web{??????????????}'

if you want tips, try running the program with -tip
""")

def tip():
    print("get good lol")

if len(argv) != 2 or "-h" in argv:
    usage()
    exit(0)

if "-tip" in argv:
    tip()
    exit(0)

h = md5(argv[1].encode('utf-8')).hexdigest()

if h in flag_hashes:
    print("Success! You validated flag nb %d" % (flag_hashes.index(h) + 1))
else:
    print("Failed! try again")
